routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
 */

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'EmployeeController@index')->name('home');
// Route::resource('employees', 'EmployeeController');
Route::resource('employees', 'EmployeeController')->except(['update']);
Route::put('/employees/{id}/{version}', 'EmployeeController@update')->name('employees.update');
Route::get('/audit', 'AuditController@index');
Route::resource('products', 'ProductsController')->only(['index', 'update']);
Route::resource('transactions', 'TransactionsController')->only(['index']);
Route::put('transactions', 'TransactionsController@transfer')->name('transfer');

resources/views/audit.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <table class="table table-striped">
        <thead class="thead-dark">
            <tr>
                <th scope="col">Model</th>
                <th scope="col">Action</th>
                <th scope="col">User</th>
                <th scope="col">Time</th>
                <th scope="col">Old Values</th>
                <th scope="col">New Values</th>
            </tr>
        </thead>
        <tbody id="audits">
            @foreach($audits as $audit)
            <tr>
                <td>{{ $audit->auditable_type }} (id: {{ $audit->auditable_id }})</td>
                <td>{{ $audit->event }}</td>
                <td>{{ $audit->user->name }}</td>
                <td>{{ $audit->created_at }}</td>
                <td>
                    <table class="table table-borderless">
                        @foreach($audit->old_values as $attribute => $value)
                        <tr>
                            <td><b>{{ $attribute }}</b></td>
                            <td>{{ $value }}</td>
                        </tr>
                        @endforeach
                    </table>
                </td>
                <td>
                    <table class="table">
                        @foreach($audit->new_values as $attribute => $value)
                        <tr>
                            <td><b>{{ $attribute }}</b></td>
                            <td>{{ $value }}</td>
                        </tr>
                        @endforeach
                    </table>
                </td>
            </tr>
            @endforeach
        </tbody>
    </table>

</div>
@endsection

resources/views/edit.blade.php
@extends('layouts.app')

@section('content')
<div class="container">

    <div class="pull-right">
        <a class="btn btn-primary" href="{{ route('employees.index') }}"> Back</a>
    </div>
    <br>

    <div class="row">
        <div class="col-lg-12 margin-tb">
            <div class="pull-left">
                <h2>Edit Employee</h2>
            </div>
        </div>
    </div>

    @if ($errors->any())
    <div class="alert alert-danger">
        <strong>Whoops!</strong> There were some problems with your input.<br><br>
        <ul>
            @foreach ($errors->all() as $error)
            <li>{{ $error }}</li>
            @endforeach
        </ul>
    </div>
    @endif

    <form action="{{ route('employees.update', ['id' => $employee->id, 'version' => $employee->updated_at]) }}" method="POST">
        @csrf
        @method('PUT')

        <div class="row">
            <div class="col-xs-12 col-sm-12 col-md-12">
                <div class="form-group">
                    <strong>Name:</strong>
                    <input type="text" name="name" value="{{ $employee->name }}" class="form-control"
                        placeholder="Name">
                </div>
            </div>
            <div class="col-xs-12 col-sm-12 col-md-12">
                <div class="form-group">
                    <strong>Phone:</strong>
                    <input type="text" name="phone" value="{{ $employee->phone }}" class="form-control"
                        placeholder="Phone">

                </div>
            </div>
            <div class="col-xs-12 col-sm-12 col-md-12">
                <div class="form-group">
                    <strong>Adress:</strong>
                    <textarea class="form-control" style="height:150px" name="address"
                        placeholder="Adress">{{ $employee->address }}</textarea>
                </div>
            </div>
            <div class="col-xs-12 col-sm-12 col-md-12">
                <div class="form-group">
                    <strong>Department:</strong>
                    <select name="department" id="department" class="form-control">
                        @foreach ($departments as $value)
                        <option value="{{ $value }}" {{ ( $value == $employee->department) ? 'selected' : '' }}>
                            {{ $value }}
                        </option>
                        @endforeach
                    </select>
                </div>
            </div>
            <div class="col-xs-12 col-sm-12 col-md-12">
                <div class="form-group">
                    <strong>Version:</strong>
                    <input id="version" type="text" class="form-control"
                            name="version" value="{{ $employee->updated_at }}" disabled>
                </div>
            </div>
            <div class="col-xs-12 col-sm-12 col-md-12 text-center">
                <button type="submit" class="btn btn-primary">Submit</button>
            </div>
        </div>

    </form>
</div>
@endsection

resources/views/home.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header ">Employee</div>

                {{-- create new employee --}}
                <div class="card-body">
                    <form method="POST" action="{{ route('employees.store') }}">
                        @csrf

                        <div class="form-group row">
                            <label for="name" class="col-md-4 col-form-label text-md-right">{{ __('Name') }}</label>

                            <div class="col-md-6">
                                <input id="name" type="text" class="form-control @error('name') is-invalid @enderror"
                                    name="name" value="{{ old('name') }}" required autocomplete="name" autofocus>

                                @error('name')
                                <span class="invalid-feedback" role="alert">
                                    <strong>{{ $message }}</strong>
                                </span>
                                @enderror
                            </div>
                        </div>

                        <div class="form-group row">
                            <label for="phone" class="col-md-4 col-form-label text-md-right">{{ __('Phone') }}</label>

                            <div class="col-md-6">
                                <input id="phone" type="text" class="form-control @error('phone') is-invalid @enderror"
                                    name="phone" value="{{ old('phone') }}" required autocomplete="phone" autofocus>

                                @error('phone')
                                <span class="invalid-feedback" role="alert">
                                    <strong>{{ $message }}</strong>
                                </span>
                                @enderror
                            </div>
                        </div>

                        <div class="form-group row">
                            <label for="address"
                                class="col-md-4 col-form-label text-md-right">{{ __('Address') }}</label>

                            <div class="col-md-6">
                                <textarea name="address" id="address"
                                    class="form-control @error('address') is-invalid @enderror" required
                                    autocomplete="address" autofocus></textarea>

                                @error('address')
                                <span class="invalid-feedback" role="alert">
                                    <strong>{{ $message }}</strong>
                                </span>
                                @enderror
                            </div>
                        </div>

                        <div class="form-group row">
                            <label for="department"
                                class="col-md-4 col-form-label text-md-right">{{ __('Department') }}</label>

                            <div class="col-md-6">
                                <select name="department" id="department"
                                    class="form-control @error('department') is-invalid @enderror" required
                                    autocomplete="department" autofocus>
                                    <option value="" selected disabled>Select department</option>
                                    <option value="Information Technology (IT)">Information Technology (IT)</option>
                                    <option value="Human Resource (HR)">Human Resource (HR)</option>
                                    <option value="Admin">Admin</option>
                                    <option value="Technical">Technical</option>
                                    <option value="Customer Service (CS)">Customer Service (CS)</option>
                                    <option value="Support Team">Support Team</option>
                                </select>

                                @error('department')
                                <span class="invalid-feedback" role="alert">
                                    <strong>{{ $message }}</strong>
                                </span>
                                @enderror
                            </div>
                        </div>

                        <div class="text-center">
                            <input type="submit" class="btn btn-success ml-auto" value="Submit">
                        </div>

                    </form>
                </div>
            </div>
        </div>
    </div>
    <br>
    {{-- table of emplyee --}}
    <table class="table-striped" style="width: 100%">
        <thead>
            <tr>
                <th>Name</th>
                <th>Phone</th>
                <th>Address</th>
                <th>Department</th>
                <th style="text-align: center">Action</th>
            </tr>
        </thead>
        <tbody>
            @if (count($employees)>0)
            @foreach ($employees as $emp)
            <tr>
                <td width="20%">{{$emp->name}}</td>
                <td width="15%">{{$emp->phone}}</td>
                <td width="28%">{{$emp->address}}</td>
                <td width="20%">{{$emp->department}}</td>
                <td width="17%">
                    <div class="row">
                        <a class="btn btn-success" href="{{ route('employees.show', $emp->id) }}">View</a>
                        &nbsp;
                        <form action="{{ route('employees.destroy',$emp->id) }}" method="POST">
                            <a class="btn btn-primary" href="{{ route('employees.edit',$emp->id) }}">Edit</a>
                            @csrf
                            @method('DELETE')
                            <button type="submit" class="btn btn-danger"
                                onclick="return confirm('Are you sure you want to delete this item?');">Delete</button>
                        </form>
                    </div>
                    
                </td>
            </tr>
            @endforeach
            @else
            <tr>
                <td class="text-center" colspan="5">No Employee found</td>
            </tr>
            @endif

        </tbody>
    </table>
</div>

@endsection

resources/views/products.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    {{-- table of products --}}
    <table class="table table-striped" width="100%">
        <thead>
            <tr>
                <th>ID</th>
                <th>Stock</th>
                <th style="text-align: center">Action</th>
            </tr>
        </thead>
        <tbody>
            @if (count($products)>0)
            @foreach ($products as $product)
            <tr>
                <td>{{$product->id}}</td>
                <td>{{$product->stock}}</td>
                <td style="text-align: center">

                    <form action="{{ route('products.update',$product->id) }}" method="POST">
                        @csrf
                        @method('PUT')
                        <button type="submit" class="btn btn-primary"
                            onclick="return confirm('Purchase one item?');">Buy</button>
                    </form>
                </td>
            </tr>
            @endforeach
            @else
            <tr>
                <td class="text-center" colspan="5">No products found</td>
            </tr>
            @endif

        </tbody>
    </table>
</div>

@endsection

resources/views/transfers.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    @if(session()->has('message'))
    <div class="alert alert-success">
        {{ session()->get('message') }}
    </div>
    @endif
    <br>
    {{-- create new transfer --}}

    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header ">Employee</div>
                <div class="card-body">
                    <form method="POST" action="{{ route('transfer') }}">
                        @csrf
                        @method('PUT')

                        <div class="form-group row">
                            <label for="balance"
                                class="col-md-4 col-form-label text-md-right">{{ __('Balance') }}</label>

                            <div class="col-md-6">
                                <input id="balance" type="text"
                                    class="form-control @error('balance') is-invalid @enderror" name="balance"
                                    value="{{ Auth::user()->balance}}" required autocomplete="balance" autofocus
                                    disabled>

                                @error('balance')
                                <span class="invalid-feedback" role="alert">
                                    <strong>{{ $message }}</strong>
                                </span>
                                @enderror
                            </div>
                        </div>

                        <div class="form-group row">
                            <label for="amount"
                                class="col-md-4 col-form-label text-md-right">{{ __('Transfer amount (RM)') }}</label>

                            <div class="col-md-6">
                                <input id="amount" type="number"
                                    class="form-control @error('amount') is-invalid @enderror" name="amount"
                                    value="{{ old('amount') }}" required autocomplete="amount" autofocus>

                                @error('amount')
                                <span class="invalid-feedback" role="alert">
                                    <strong>{{ $message }}</strong>
                                </span>
                                @enderror
                            </div>
                        </div>
                        <input type="text" name="from_user" value="{{Auth::user()->id}}" hidden>
                        <div class="form-group row">
                            <label for="to"
                                class="col-md-4 col-form-label text-md-right">{{ __('Transfer to') }}</label>

                            <div class="col-md-6">
                                <select name="to_user" id="to_user" class="form-control">
                                    <option value="" selected disabled>Select User</option>
                                    @foreach ($users as $user)
                                    @if ($user->id != Auth::user()->id)
                                    <option value="{{ $user->id }}">{{ $user->name }}</option>
                                    @endif

                                    @endforeach
                                </select>

                                @error('to')
                                <span class="invalid-feedback" role="alert">
                                    <strong>{{ $message }}</strong>
                                </span>
                                @enderror
                            </div>
                        </div>

                        <div class="text-center">
                            <input type="submit" class="btn btn-success ml-auto" value="Transfer">
                        </div>

                    </form>
                </div>
            </div>
        </div>
        <br><br><br>
        <table class="table table-striped">
            <thead>
                <tr>
                    <th>Id</th>
                    <th>From</th>
                    <th>To</th>
                    <th>Amount (RM)</th>
                    <th>Time</th>
                </tr>
            </thead>
            <tbody>
                @foreach ($transactions as $transaction)
                <tr>
                    <td>{{$transaction->id}}</td>
                    <td>{{$transaction->from->name}}</td>
                    <td>{{$transaction->to->name}}</td>
                    <td>{{$transaction->amount}}</td>
                    <td>{{$transaction->updated_at}}</td>
                </tr>
                @endforeach
            </tbody>
        </table>
    </div>
</div>
</div>
@endsection